# configuration générale du projet dbt
name: 'dataops_olist'
version: '1.0.0'
config-version: 2

profile: 'dataops_olist'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  dataops_olist:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table