dataops_olist:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_dw
      user: dataops_user
      password: dataops_pass
      port: 5432
      dbname: dataops_dw
      schema: public
      threads: 4