services:
  postgres_dw:
    image: postgres:13
    container_name: postgres_dw # c'est notre Data Warehouse, pas celui d'Airflow
    environment:
      POSTGRES_USER: dataops_user
      POSTGRES_PASSWORD: dataops_pass
      POSTGRES_DB: dataops_dw
    ports:
      - "5433:5432"
    volumes:
      - postgres-dw-volume:/var/lib/postgresql/data

volumes:
  postgres-dw-volume: